// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxSLwLDvT6SRsvLmDIGk7wiOYHtOuu8mo',
    appId: '1:317373417952:android:9fc24d5803ed11ee2f8385',
    messagingSenderId: '317373417952',
    projectId: 'topai-assignment',
    storageBucket: 'topai-assignment.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKYuB0jRh2SSElptZdju5i3zMp_pXPrQ8',
    appId: '1:317373417952:ios:7ed577423e37da672f8385',
    messagingSenderId: '317373417952',
    projectId: 'topai-assignment',
    storageBucket: 'topai-assignment.firebasestorage.app',
    androidClientId: '317373417952-8vpiaeqhl99fi1n0aqrbp5dajqmuojrh.apps.googleusercontent.com',
    iosClientId: '317373417952-lq49tgmcl42grhohjbfh9kq4ij82hrap.apps.googleusercontent.com',
    iosBundleId: 'com.topai.topai24',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtfZbh60OpFTfgusXZROlvXI0iap1J9iY',
    appId: '1:317373417952:web:c356324f11dd21b02f8385',
    messagingSenderId: '317373417952',
    projectId: 'topai-assignment',
    authDomain: 'topai-assignment.firebaseapp.com',
    storageBucket: 'topai-assignment.firebasestorage.app',
  );
}
